#!/bin/bash

#ddev-generated

## Description: Launch a browser with latest backstop results
## Usage: backstopjs-report <environment_folder>
## Aliases: backstop-report, bjsr
## Example: "ddev backstop-report local"

FOLDER=${1:-local}

REPORT_PATH=tests/backstopjs/$FOLDER/backstop_data/html_report/index.html

if ! [ -f $REPORT_PATH ]; then
  echo "Report does not exist."
  exit 0;
fi

case $OSTYPE in
  linux-gnu)
    xdg-open $REPORT_PATH
    ;;
  "darwin"*)
    open $REPORT_PATH
    ;;
  "win*"* | "msys"*)
    start $REPORT_PATH
    ;;
esac
